theme: jekyll-theme-minimal
title: ProtectronBot Documentation
description: Your guide to using and configuring ProtectronBot, the ultimate Telegram group management bot.

logo: /assets/img/protectronbot.jpeg

# Enable Google Analytics
google_analytics: G-CSHN6P3QZE
